[[variable]]
key = "http_trigger_path"
value = "/hello"
desc = "Http trigger path /??? "
optional = false

[[variable]]
key = "http_trigger_method"
value = "GET"
desc = "Http trigger method POST/GET"
optional = false

[[dependency]]
executable = "componentize-py"
required_version = ">=0.17.0"
installation_help = "install by running 'pip install componentize-py' or upgrade an existing installation with 'pip install componentize-py --upgrade --force-reinstall'"