name = "my-typescript-application"
component_target = 'my-typescript-application:0.1.0'

[[trigger]]
type = 'http'
path = '/mypath'
method = 'POST'

[env]
HELLO_MESSAGE = "you"

[capabilities]
allowed-outgoing-url = ["https://dummyjson.com/*"]
