[[variable]]
key = "schedule"
value = "0 0 */12 * * *"
desc = "Cron-schedule '0 0 */12 * * *' runs once every 12 hour"
optional = false

[[variable]]
key = "timeout"
value = 30
var_type = "Int"
desc = "Max-execution time in seconds"
optional = false

[[dependency]]
executable = "rustc"
required_version = ">=1.85"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"

[[dependency]]
executable = "cargo"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"

[[dependency]]
executable = "rustup"
installation_help = "install rust from here: https://www.rust-lang.org/tools/install"
