name = "{{name}}"
version = "0.1.0"

[build.dev]
build = "cargo build --target=wasm32-wasip2"
wasm_path = "target/wasm32-wasip2/debug/{{name | replace(from="-", to="_") }}.wasm"

[build.prod]
build = "cargo build --target=wasm32-wasip2 --release"
wasm_path = "target/wasm32-wasip2/release/{{name | replace(from="-", to="_") }}.wasm"