name = "my-project"
version = "1.0.0"

[registry.metadata]
authors = [""]
description = "Description of my-project"
license = ""
categories = [""]

[build.dev]
build = "dotnet build"
wasm_path = "./bin/Debug/net10.0/wasi-wasm/native/my-project.wasm"

[build.prod]
build = "dotnet build . --configuration Release"
wasm_path = "./bin/Release/net10.0/wasi-wasm/publish/my-project.wasm"
