name = "{{name}}"
version = "0.1.0"

[registry.metadata]
authors = [""]
description = "Description of {{name}}"
license = ""
categories = [""]

[build.dev]
build = "dotnet build"
wasm_path = "./bin/Debug/net10.0/wasi-wasm/native/{{name}}.wasm"

[build.prod]
build = "dotnet build . --configuration Release"
wasm_path = "./bin/Release/net10.0/wasi-wasm/publish/{{name}}.wasm"
