#region HEIM-AUTOGENERATED
using System.Runtime.CompilerServices;

namespace DemoGeolocationWorld.wit.exports.heim.demoGeolocation.v1_0_0;

// these methods are temporarily accessing methods on System.Threading.Thread via UnsafeAccessor until we have it in public API, probably in WASI preview3 and promises
internal static class WasiEventLoop
{
    public static void PollWasiEventLoopUntilResolved(Task mainTask)
    {
        CallPollWasiEventLoopUntilResolvedVoid((Thread)null!, mainTask);

        //https://github.com/dotnet/runtime/blob/9a02107e78699dbd4b4f2f12277bcc6dbd889e89/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.Unix.cs#L32
        [UnsafeAccessor(UnsafeAccessorKind.StaticMethod, Name = "PollWasiEventLoopUntilResolvedVoid")]
        static extern void CallPollWasiEventLoopUntilResolvedVoid(Thread t, Task mainTask);
    }
}

#endregion HEIM-AUTOGENERATED
