name = "my-python-application"
version = "0.1.0"

[registry.metadata]
authors = [""]
description = "Description of my-python-application"
license = ""
categories = [""]

[build.dev]
build = "componentize-py --world-module nor2_world componentize app -o my-python-application.wasm"
wasm_path = "./my-python-application.wasm"

[build.prod]
build = "componentize-py --world-module nor2_world componentize app -o my-python-application.wasm"
wasm_path = "./my-python-application.wasm"
