name = "{{name}}"
version = "0.1.0"


[build.dev]
build = "tinygo build -target=wasip2 --wit-package ./wit/proxy.wit --wit-world nor2:heim/nor2-world -o bin/{{name | replace(from="-", to="_") }}.wasm main.go"
wasm_path = "bin/{{name | replace(from="-", to="_") }}.wasm"

[build.prod]
build = "tinygo build -target=wasip2 --wit-package ./wit/proxy.wit --wit-world nor2:heim/nor2-world -gc=conservative -opt=z -o bin/{{name | replace(from="-", to="_") }}.wasm main.go"
wasm_path = "bin/{{name | replace(from="-", to="_") }}.wasm"