[[variable]]
key = "http_trigger_path"
value = "/hello"
desc = "Http trigger path /??? "
optional = false

[[variable]]
key = "http_trigger_method"
value = "GET"
desc = "Http trigger method POST/GET"
optional = false

[[dependency]]
executable = "TinyGo" 
required_version = ">=0.33.0"
installation_help = "Download TinyGo at https://tinygo.org/getting-started/install/"

[[dependency]]
executable = "Go"
required_version = ">=1.20.0"
installation_help = "Download Go at https://go.dev/doc/install" 

